/**
 * @pokeralph/core
 *
 * Core business logic for PokéRalph - the autonomous development orchestrator.
 * This package contains types, services, and the main orchestrator.
 * It has zero UI dependencies and runs in any environment.
 */

// Version export for debugging
export const VERSION = "0.1.0";

// Main Orchestrator - primary entry point
export {
  Orchestrator,
  type AddTaskInput,
  type UpdateTaskInput,
} from "./orchestrator.ts";

// Re-export services
export {
  FileManager,
  FileNotFoundError,
  ValidationError,
  // PromptBuilder
  PromptBuilder,
  type TaskContext,
  PRD_OUTPUT_SCHEMA,
  TASKS_OUTPUT_SCHEMA,
  PROGRESS_UPDATE_SCHEMA,
  COMPLETION_SIGIL,
  // ClaudeBridge
  ClaudeBridge,
  type ClaudeBridgeOptions,
  type ClaudeMode,
  type ExitCallback,
  type OutputCallback,
  // ProgressWatcher
  ProgressWatcher,
  type ProgressWatcherOptions,
  type ProgressWatcherEvents,
  // FeedbackRunner
  FeedbackRunner,
  type FeedbackRunnerOptions,
  type FeedbackLoopResult,
  STANDARD_LOOPS,
  type StandardLoop,
  // GitService
  GitService,
  type GitServiceOptions,
  type FileStatus,
  type GitStatus,
  type CommitInfo,
  // BattleOrchestrator
  BattleOrchestrator,
  type BattleOrchestratorDependencies,
  type BattleOrchestratorEvents,
  // PlanService
  PlanService,
  type PlanServiceDependencies,
  type PlanServiceEvents,
  type PlanningState,
  type PRDParseResult,
  type TasksParseResult,
  type PRDExtractionErrorCode,
  // Zod schemas
  ConfigSchema,
  TaskSchema,
  PRDSchema,
  ProgressSchema,
  BattleSchema,
  IterationSchema,
  ExecutionModeSchema,
  TaskStatusSchema,
  ProgressStatusSchema,
  BattleStatusSchema,
  FeedbackResultSchema,
  FeedbackResultsSchema,
  PRDMetadataSchema,
  // ProjectDetection
  detectProject,
  getSuggestedConfig,
  hasLowTrustDefaults,
  getDetectionGuidance,
  PROJECT_DEFAULTS,
  UNKNOWN_PROJECT_EXPLANATION,
  type ProjectType,
  type ProjectDetection,
  // PreflightService
  PreflightService,
  tokenizeCommand,
  toPreflightCheckResultDTO,
  toPreflightReportDTO,
  generatePreflightToken,
  validatePreflightToken,
  assessTaskRisk,
  type PreflightCheckCategory,
  type PreflightCheckSeverity,
  type PreflightContext,
  type PreflightResult,
  type FixResult,
  type PreflightCheck,
  type PreflightCheckResult,
  type PreflightCheckResultDTO,
  type PreflightSummary,
  type PreflightReport,
  type PreflightReportDTO,
  type TaskRisk,
  type TaskRiskFactor,
  // DryRunService
  DryRunService,
  redactSensitiveData,
  predictAffectedFiles,
  assessFileConfidence,
  estimateIterations,
  assessIterationConfidence,
  assessDurationConfidence,
  countTokens,
  type ConfidenceLevel,
  type DryRunResult,
  type DryRunContext,
  // RecoveryService
  classifyFailure,
  getFailureSeverity,
  getRecoveryOptions,
  getFailureMessage,
  getRecoverySuggestion,
  getAllRecoverySuggestions,
  FeedbackLoopError,
  TimeoutError,
  ClaudeError,
  SystemError,
  CancellationError,
  CrashError,
  type FailureType,
  type RecoveryAction,
  type BattleFailure,
  type BattleContext,
  type FailureSeverity,
  // CheckpointService
  CommitCheckpointStorage,
  PatchCheckpointStorage,
  getCheckpointStorage,
  createCheckpoint,
  restoreCheckpoint,
  createInitialCheckpoint,
  findCheckpointByIteration,
  getInitialCheckpoint,
  validateCheckpoint,
  cleanupCheckpoints,
  getCheckpointsToRemove,
  DEFAULT_RETENTION_POLICY,
  type CheckpointStorageType,
  type Checkpoint,
  type CheckpointStorage,
  type RollbackResult,
  type RollbackOptions,
  type CheckpointRetentionPolicy,
  // RecommendationService
  computeTaskRecommendation,
  buildProjectContext,
  getTaskRecommendations,
  getTopRecommendation,
  extractDependencies,
  checkDependencies,
  countBlockedTasks,
  calculateMomentum,
  type RecommendationReasonType,
  type RecommendationReason,
  type TaskRecommendation,
  type ProjectContext,
  type RecommendationsResult,
  // SummaryService
  generateIterationSummary,
  generateBattleSummaries,
  parseClaudeActions,
  parseDiffSummary,
  extractReasoning,
  extractLearnings,
  generateHeadline,
  summarizeFeedbackResults,
  buildFileSummariesFromIteration,
  type IterationSummary,
  type FileSummary,
  type FeedbackSummary,
  type ClaudeAction,
  type SummaryContext,
} from "./services/index.ts";

// Re-export all types
export {
  // Configuration
  type Config,
  type ExecutionMode,
  DEFAULT_CONFIG,
  // Task
  type Task,
  TaskStatus,
  // PRD
  type PRD,
  type PRDMetadata,
  // Progress
  type Progress,
  type ProgressStatus,
  type FeedbackResult,
  type FeedbackResults,
  createInitialProgress,
  // Iteration
  type Iteration,
  type IterationResult,
  createIteration,
  // Battle
  type Battle,
  type BattleStatus,
  createBattle,
  // Events
  type EventType,
  type BaseEvent,
  type PokéRalphEvent,
  createEvent,
  // Planning events
  type PlanningStartedEvent,
  type PlanningOutputEvent,
  type PlanningQuestionEvent,
  type PlanningCompletedEvent,
  type PlanningStartedPayload,
  type PlanningOutputPayload,
  type PlanningQuestionPayload,
  type PlanningCompletedPayload,
  // Battle events
  type BattleStartEvent,
  type BattlePauseEvent,
  type BattleResumeEvent,
  type BattleCancelEvent,
  type BattleCompleteEvent,
  type BattleFailedEvent,
  type BattleStartPayload,
  type BattlePausePayload,
  type BattleResumePayload,
  type BattleCancelPayload,
  type BattleCompletePayload,
  type BattleFailedPayload,
  // Iteration events
  type IterationStartEvent,
  type IterationEndEvent,
  type IterationOutputEvent,
  type IterationStartPayload,
  type IterationEndPayload,
  type IterationOutputPayload,
  // Progress events
  type ProgressUpdateEvent,
  type CompletionDetectedEvent,
  type ProgressUpdatePayload,
  type CompletionDetectedPayload,
  // Feedback events
  type FeedbackStartEvent,
  type FeedbackResultEvent,
  type FeedbackStartPayload,
  type FeedbackResultPayload,
  // Approval events
  type AwaitApprovalEvent,
  type ApprovalReceivedEvent,
  type AwaitApprovalPayload,
  type ApprovalReceivedPayload,
  // System events
  type ErrorEvent,
  type WarningEvent,
  type ErrorPayload,
  type WarningPayload,
} from "./types/index.ts";
